site:
  title: Ra
  description: Ra is an open personal knowledge base.
  keywords: nocodb, git, static web site, html
  theme: default
  language: en-US
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  # root-path: /nocodb
  # set cdn path:
  cdn-path: https://cdn.jsdelivr.net/npm
  navigation:
    - title: Python
      uri: /books/python/index.html
    - title: OS
      uri: /books/os/index.html
    - title: NocoDB
      uri: /books/nocodb/index.html
    - title: Pandas
      uri: /books/pandas/index.html
    - title: Scrapy
      uri: /books/scrapy/index.html
    - title: Lxml
      uri: /books/lxml/index.html
    - title: Books
      uri: /books/books/index.html
    - title: Discuss
      uri: https://github.com/ittakestwo-hz/nocodb/discussions
      external: true
  git:
    base-url: https://github.com/ittakestwo-hz/nocodb/blob/main/source
  contact:
    name: ittakestwo-hz
    github: https://github.com/ittakestwo-hz/nocodb
    twitter: https://twitter.com/ittakestwo-hz
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: true
    # any custom styles used in theme:
    # code-font: Monaco
  # integration:
  #   comment:
  #     provider: disqus
  #     name: nocodb
  #   analytics:
  #     provider: google
  #     gtag: G-5Z40K7NBL5

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt

# you can add any items:
